<?php

use App\Http\Controllers\AahaasCallEndController;
use App\Http\Controllers\AahaasCallSessionController;
use App\Http\Controllers\AahaasCallTurnController;
use App\Http\Controllers\AahaasChatGpt3vEndController;
use App\Http\Controllers\AahaasChatGpt3vHoldMusicController;
use App\Http\Controllers\AahaasChatGpt3vPackagePrefetchController;
use App\Http\Controllers\AahaasChatGpt3vPackageStatusController;
use App\Http\Controllers\AahaasChatGpt3vSessionController;
use App\Http\Controllers\AahaasChatGpt3vTurnController;
use App\Http\Controllers\FourVChatGptAssisEndController;
use App\Http\Controllers\FourVChatGptAssisHoldMusicController;
use App\Http\Controllers\FourVChatGptAssisPackagePrefetchController;
use App\Http\Controllers\FourVChatGptAssisPackageStatusController;
use App\Http\Controllers\FourVChatGptAssisSessionController;
use App\Http\Controllers\FourVChatGptAssisTurnController;
use App\Http\Controllers\AiAssistentFinalTestEndController;
use App\Http\Controllers\AiAssistentFinalTestPackagePrefetchController;
use App\Http\Controllers\AiAssistentFinalTestPackageStatusController;
use App\Http\Controllers\AiAssistentFinalTestSessionController;
use App\Http\Controllers\AiAssistentFinalTestTurnController;
use App\Http\Controllers\FiveVChatGptAssisEndController;
use App\Http\Controllers\FiveVChatGptAssisHoldMusicController;
use App\Http\Controllers\FiveVChatGptAssisPackagePrefetchController;
use App\Http\Controllers\FiveVChatGptAssisPackageStatusController;
use App\Http\Controllers\FiveVChatGptAssisSessionController;
use App\Http\Controllers\FiveVChatGptAssisTurnController;
use App\Http\Controllers\UvinduCallEndController;
use App\Http\Controllers\UvinduCallSessionController;
use App\Http\Controllers\UvinduCallTurnController;
use App\Http\Controllers\AiCallController;
use App\Http\Controllers\ElevenLabsSignedUrlController;
use App\Http\Controllers\RecordDownloadController;
use App\Http\Controllers\RecordsListController;
use App\Http\Controllers\RecordShowController;
use App\Http\Controllers\ReceptionCallEndController;
use App\Http\Controllers\ReceptionCallSessionController;
use App\Http\Controllers\ReceptionCallTurnController;
use App\Http\Controllers\TextAiVoiceController;
use App\Http\Controllers\TextToSpeechController;
use App\Http\Controllers\TripCallEndController;
use App\Http\Controllers\TripCallSessionController;
use App\Http\Controllers\TripCallTurnController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => response()->json([
    'status' => 'ok',
    'elevenlabsConfigured' => filled(env('ELEVENLABS_API_KEY')),
    'openaiConfigured' => filled(env('OPENAI_API_KEY')),
]));
Route::get('/elevenlabs/signed-url', ElevenLabsSignedUrlController::class);
Route::options('/elevenlabs/signed-url', fn () => response('', 204));
Route::post('/tts', TextToSpeechController::class);
Route::post('/ai-call', AiCallController::class);
Route::post('/text-ai-voice', TextAiVoiceController::class);
Route::post('/trip-call/session', TripCallSessionController::class);
Route::post('/trip-call/turn', TripCallTurnController::class);
Route::post('/trip-call/end', TripCallEndController::class);
Route::post('/aahaas-call/session', AahaasCallSessionController::class);
Route::post('/aahaas-call/turn', AahaasCallTurnController::class);
Route::post('/aahaas-call/end', AahaasCallEndController::class);
Route::options('/aahaas-call/session', fn () => response('', 204));
Route::options('/aahaas-call/turn', fn () => response('', 204));
Route::options('/aahaas-call/end', fn () => response('', 204));
Route::post('/ai-assistent-final-test/session', AiAssistentFinalTestSessionController::class);
Route::post('/ai-assistent-final-test/turn', AiAssistentFinalTestTurnController::class);
Route::post('/ai-assistent-final-test/end', AiAssistentFinalTestEndController::class);
Route::post('/ai-assistent-final-test/package-prefetch', AiAssistentFinalTestPackagePrefetchController::class);
Route::post('/ai-assistent-final-test/package-status', AiAssistentFinalTestPackageStatusController::class);
Route::options('/ai-assistent-final-test/session', fn () => response('', 204));
Route::options('/ai-assistent-final-test/turn', fn () => response('', 204));
Route::options('/ai-assistent-final-test/end', fn () => response('', 204));
Route::options('/ai-assistent-final-test/package-prefetch', fn () => response('', 204));
Route::options('/ai-assistent-final-test/package-status', fn () => response('', 204));
Route::get('/aahaas-chatgpt-3v/hold-music', AahaasChatGpt3vHoldMusicController::class);
Route::post('/aahaas-chatgpt-3v/session', AahaasChatGpt3vSessionController::class);
Route::post('/aahaas-chatgpt-3v/turn', AahaasChatGpt3vTurnController::class);
Route::post('/aahaas-chatgpt-3v/end', AahaasChatGpt3vEndController::class);
Route::post('/aahaas-chatgpt-3v/package-prefetch', AahaasChatGpt3vPackagePrefetchController::class);
Route::post('/aahaas-chatgpt-3v/package-status', AahaasChatGpt3vPackageStatusController::class);
Route::options('/aahaas-chatgpt-3v/session', fn () => response('', 204));
Route::options('/aahaas-chatgpt-3v/turn', fn () => response('', 204));
Route::options('/aahaas-chatgpt-3v/end', fn () => response('', 204));
Route::options('/aahaas-chatgpt-3v/package-prefetch', fn () => response('', 204));
Route::options('/aahaas-chatgpt-3v/package-status', fn () => response('', 204));
Route::get('/5v-chatgpt-assis/hold-music', FiveVChatGptAssisHoldMusicController::class);
Route::post('/5v-chatgpt-assis/session', FiveVChatGptAssisSessionController::class);
Route::post('/5v-chatgpt-assis/turn', FiveVChatGptAssisTurnController::class);
Route::post('/5v-chatgpt-assis/end', FiveVChatGptAssisEndController::class);
Route::post('/5v-chatgpt-assis/package-prefetch', FiveVChatGptAssisPackagePrefetchController::class);
Route::post('/5v-chatgpt-assis/package-status', FiveVChatGptAssisPackageStatusController::class);
Route::options('/5v-chatgpt-assis/session', fn () => response('', 204));
Route::options('/5v-chatgpt-assis/turn', fn () => response('', 204));
Route::options('/5v-chatgpt-assis/end', fn () => response('', 204));
Route::options('/5v-chatgpt-assis/package-prefetch', fn () => response('', 204));
Route::options('/5v-chatgpt-assis/package-status', fn () => response('', 204));
Route::get('/4v-chatgpt-assis/hold-music', FourVChatGptAssisHoldMusicController::class);
Route::post('/4v-chatgpt-assis/session', FourVChatGptAssisSessionController::class);
Route::post('/4v-chatgpt-assis/turn', FourVChatGptAssisTurnController::class);
Route::post('/4v-chatgpt-assis/end', FourVChatGptAssisEndController::class);
Route::post('/4v-chatgpt-assis/package-prefetch', FourVChatGptAssisPackagePrefetchController::class);
Route::post('/4v-chatgpt-assis/package-status', FourVChatGptAssisPackageStatusController::class);
Route::options('/4v-chatgpt-assis/session', fn () => response('', 204));
Route::options('/4v-chatgpt-assis/turn', fn () => response('', 204));
Route::options('/4v-chatgpt-assis/end', fn () => response('', 204));
Route::options('/4v-chatgpt-assis/package-prefetch', fn () => response('', 204));
Route::options('/4v-chatgpt-assis/package-status', fn () => response('', 204));
Route::post('/uvindu-call/session', UvinduCallSessionController::class);
Route::post('/uvindu-call/turn', UvinduCallTurnController::class);
Route::post('/uvindu-call/end', UvinduCallEndController::class);
Route::options('/uvindu-call/session', fn () => response('', 204));
Route::options('/uvindu-call/turn', fn () => response('', 204));
Route::options('/uvindu-call/end', fn () => response('', 204));
Route::post('/reception-call/session', ReceptionCallSessionController::class);
Route::post('/reception-call/turn', ReceptionCallTurnController::class);
Route::post('/reception-call/end', ReceptionCallEndController::class);
Route::get('/records', RecordsListController::class);
Route::get('/records/{recordType}/{publicId}', RecordShowController::class)
    ->whereIn('recordType', ['service_call', 'trip_plan']);
Route::get('/records/{recordType}/{publicId}/download', RecordDownloadController::class)
    ->whereIn('recordType', ['service_call', 'trip_plan']);
Route::options('/tts', fn () => response('', 204));
Route::options('/ai-call', fn () => response('', 204));
Route::options('/text-ai-voice', fn () => response('', 204));
Route::options('/trip-call/session', fn () => response('', 204));
Route::options('/trip-call/turn', fn () => response('', 204));
Route::options('/trip-call/end', fn () => response('', 204));
Route::options('/reception-call/session', fn () => response('', 204));
Route::options('/reception-call/turn', fn () => response('', 204));
Route::options('/reception-call/end', fn () => response('', 204));
Route::options('/records', fn () => response('', 204));
